server {
    listen 8080;
    listen [::]:8080;

    root /var/www/linux_project/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }
}
